### ISSUE TITLE
Animated list?

### ISSUE THREAD

**Issue by Atinux** [MopTym/vue-waterfall#1]
Hi!

Thank you for this great plugin!

I was thinking if it's possible to animate it via https://github.com/vuejs/vue-animated-list?

**Comment by MopTym** [comment]
Not yet, but this feature is coming soon. Thank you for your support!

**Comment by MopTym** [comment]
It is incompatible with vue-animated-list, but now you can use `watch`, `order`, `move-class` props to do the same thing. Click on the [demo](http://app.moptym.com/vue-waterfall/demo/vertical-line.html) page to see it.

**Comment by Atinux** [comment]
Nice work @MopTym :-)
