### ISSUE TITLE
Invalid default value for prop "emitter"

### ISSUE THREAD

**Issue by haffla** [MopTym/vue-waterfall#11]
Hello! I get the following warnings when using vue-waterfall. I don't seem to find the reason for this. Any idea?

![screenshot_20161023_171443](https://cloud.githubusercontent.com/assets/2844304/19627323/a050b70a-9944-11e6-9a40-3f845f17fe6a.png)

The relevant code is the following:

```
<waterfall :line-gap="200" :watch="locations">
    <waterfall-slot v-for="location in locations" :width="100" :height="100" :key="location.id">
      <h1>Test</h1>
    </waterfall-slot>
</waterfall>
```

`locations` is an array of objects.

It is working, but the 2 red warnings in the console are kind of annoying and I would like to know what's it about. I'm kind of new to vue. 

My vue version is `2.0.3`.

**Comment by MopTym** [comment]
Fixed. [8a7110b](https://github.com/MopTym/vue-waterfall/commit/8a7110b89184dfdab107c1fca33f6c8748439c01) . Thx for your feedback.

In addition, the code should be:

```js
<waterfall :line-gap="200" :watch="locations">
    <waterfall-slot v-for="(location, index) in locations" :width="100" :height="100" :key="location.id" :order="index">
      <h1>Test</h1>
    </waterfall-slot>
</waterfall>
```

**Comment by haffla** [comment]
Damn that was fast! It's working now. Great, thank you.
