### ISSUE TITLE
Percentage width

### ISSUE THREAD

**Issue by quebecCu** [MopTym/vue-waterfall#13]
How can I make a waterfall slot to be a % width of the page, instead of pixels, for example if I want a vertical waterfall which each slot to fill 50% of the page? 

Thank you!

**Comment by MopTym** [comment]
Now you can use `grow` in `v1.0.3` , like `:grow="[1, 1]"` , see [example](http://app.moptym.com/vue-waterfall/demo/vertical-line-with-grow.html) .
