### ISSUE TITLE
autoheight for vertical line direction waterfall-slot?

### ISSUE THREAD

**Issue by webtower** [MopTym/vue-waterfall#2]
Hi!

I really love your plugin but I can't figure out how to set waterfall-slot height automaticly based on waterfall-slot's custom child component.

I've tried to detect child component height on "attached" lifecycle hook (http://vuejs.org/api/#attached) using:

`this.$el.offsetHeight;`

but it always logs 0. If I could get height of child component, then I would be able to send it upwards to waterfall-slot.

**Comment by MopTym** [comment]
The slot of waterfall is a space to place your component, which like a parking space. The size of slot and custom child component should both be based on data.

Could you tell me more details about your requirement?

**Comment by webtower** [comment]
You are right, I actually can calculate content height based on data by adding some additional logic.

I thought It would be some more flexible way, for example by just rendering waterfall slot content first (custom child component), measuring its height automaticly and then setting back waterfall-slot "height" property.

**Comment by MopTym** [comment]
I got it, the keys are:

- On `attached` callback, the component probably has not yet rendered, you need to wait some time to call `this.$el.offsetHeight` .

- Use correct CSS to let the height of component be the content height.

See [this](https://gist.github.com/MopTym/1d6a75aaf95d8d5f9ab2) .

**Comment by webtower** [comment]
This exaclty solution I was looking for! You are great, thank you very much.
