### ISSUE TITLE
a transition question

### ISSUE THREAD

**Issue by callect** [MopTym/vue-waterfall#5]
I use vue-route control pages switch
I add 'keep-alive' to root, and i click to enter other page, when i turn back, the transition has been broken, seem like nothing transition.
why to happend?

**Comment by MopTym** [comment]
Could you provide a reproduction?

**Comment by callect** [comment]
Ok , you can look at this [https://jsfiddle.net/gsLmogcc/2/](url)

**Comment by MopTym** [comment]
Remove `transition` attribute from waterfall-slot, it conflicts with `move-class`.

**Comment by callect** [comment]
I do it, but nothing changed :(

**Comment by MopTym** [comment]
https://jsfiddle.net/0czjzv2w/
