### ISSUE TITLE
build的时候报错

### ISSUE THREAD

**Issue by callect** [MopTym/vue-waterfall#6]
`ERROR in d:/xampp/htdocs/thvote/~/extract-text-webpack-plugin/loader.js?{"omit":1,"extract":true,"remove":true}!d:/xampp/htdocs/thvote/~/.npminstall/vue-style-loader/1.0.0/vue-style-loader!d:/xampp/htdocs/thvote/~/.npminstall/css-loader/0.23.1/css-loader?sourceMap!d:/xampp/htdocs/thvote/~/.npminstall/vue-loader/8.5.2/vue-loader/lib/style-rewriter.js!d:/xampp/htdocs/thvote/~/.npminstall/vue-loader/8.5.2/vue-loader/lib/selector.js?type=style&index=0!d:/xampp/htdocs/thvote/~/.npminstall/vue-waterfall/0.2.2/vue-waterfall/lib/waterfall.vue
Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
    at Object.module.exports.pitch (d:\xampp\htdocs\thvote\node_modules\extract-text-webpack-plugin\loader.js:21:9)
 @ d:/xampp/htdocs/thvote/~/.npminstall/vue-waterfall/0.2.2/vue-waterfall/lib/waterfall.vue 2:0-308`

waterfall-slot.vue似乎也有同样的错误我就不贴出来了

**Comment by MopTym** [comment]
这是你项目里的错误，vue-waterfall 的构建配置里没有使用过 `extract-text-webpack-plugin`
