### ISSUE TITLE
Vue 2

### ISSUE THREAD

**Issue by avitex** [MopTym/vue-waterfall#9]
Looking at the source for `vue-waterfall`, and the vue 2 spec, lifetime hooks have been slightly changed and also the way events are used.

Without understanding the magic, I changed the lifetime hooks and event emitters. [It half works](https://gyazo.com/9dbcfddb821c594175b0e0455ee7c47a), though I didn't spend to much time to see why not.
I imagine it perhaps is to do with a binding, or they way events are working now.

Have you got something in the mix, or would you like some help prior to Vue 2's release?

**Comment by MopTym** [comment]
I will release v1.0.0 which compatible with Vue 2 in the next several days.

**Comment by avitex** [comment]
Terrific, and thank you for this library

**Comment by deakster** [comment]
Looking forward to 2.0 support too :)

**Comment by bxyoung89** [comment]
Any word on this? I'm trying to add this library to a project I just started but all of the vue-waterfall-slot elements are styled with 'display:none'. I think this is because I'm on Vue 2.0 but I'm not sure.

**Comment by MopTym** [comment]
[v1.0.0](https://github.com/MopTym/vue-waterfall/releases/tag/v1.0.0)

Sorry for being late. @avitex @deakster @bxyoung89
